AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: { }
LongLineCheck: { max_line_length: 80,
  ignored_files: [
    'db/migrate', 'config/initializers', 'models/ckeditor/picture.rb'
  ]
}
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: { }
MoveModelLogicIntoModelCheck: { use_count: 4 }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: {
  ignored_files: [
    "models/ckeditor/asset.rb"
  ]
}
RemoveEmptyHelpersCheck: { }
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck: {
  except_methods: [
    "PagesController#show", "Managers::SubjectsController#index",
    "Managers::SubjectsController#create",
    "Devise::SessionsController#create", "Managers::UsersController#create",
    "Devise::SessionsController#create", "Managers::DashboardController#index",
    "Managers::CoursesController#create", "PagesController#show",
    "Managers::CoursesController#show", "Managers::UsersController#index",
    "Managers::CourseClassesController#index",
    "Managers::ClassTraineesController#index",
    "Managers::CoursesController#index"
  ]
}
RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
RemoveUnusedMethodsInModelsCheck: { except_methods: [] }
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: {
  ignored_files: [
    "app/views/managers/users/index.html.erb",
    "app/views/managers/training_frameworks/show.html.erb",
    "app/views/managers/training_frameworks/_subject.html.erb",
    "app/views/managers/courses/show.html.erb",
    "app/views/managers/documents/index.html.erb",
    "app/views/course_classes/show.html.erb"
  ]
}
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
